### ISSUE TITLE
Demultiplexing skip during setup fails

### ISSUE THREAD

**Issue by ressy** [cnobles/iGUIDE#40]
It looks like `iguide setup --skip_demultiplexing` currently fails because the config object isn't available to get_sample_list, and then the Demulti_Dir path is rejected because it already exists (because of the check_existing call).  I think if the config object is passed to get_sample_list and check_existing is removed (maybe not relevant since it should exist in this case?) it should be OK.

**Comment by cnobles** [comment]
Resolved in #51.
