### ISSUE TITLE
Processing fails for SRA read IDs

### ISSUE THREAD

**Issue by ressy** [cnobles/iGUIDE#43]
The FASTQ read identifiers supplied by the SRA look like `@SRR#######.#`, but the default readNamePattern used in the demulti and filt rules just takes the portion before the period which leads to errors due to non-unique read IDs.  Since the R scripts allow custom patterns it looks like exposing the pattern argument to the rules would allow this to work.

**Comment by cnobles** [comment]
Fixed in #50! Config parameter (readNamePattern) can be used with regex to change the readNamePattern for several parts of the pipeline.
