### ISSUE TITLE
Argument list too long error in core_stat_matrix command

### ISSUE THREAD

**Issue by ressy** [cnobles/iGUIDE#45]
I have a large number of .stat files as input to the core_stat_matrix rule, and when it tries to call collect_stats.R the shell returns an "argument list too long" error because of all the input files.  I've made it work for my case by sourcing the core_stat code as a function and using `run: R("...")` directly in the rule.  That works, but then you need an extra dependency installed in the environment too (rpy2) for Snakemake's R function to work, so it's a bit different from the current code.

Here's what I'm doing, for reference: https://github.com/cnobles/iGUIDE/compare/master...ressy:snakemake-rpy

**Comment by ressy** [comment]
Whoops, tests fail because I added rpy2 to my requirements but not the build.  I'll check that out.

**Comment by ressy** [comment]
@cnobles this is the `directory()` thing I was trying to remember earlier, may help with that approach instead: https://snakemake.readthedocs.io/en/stable/snakefiles/rules.html#directories-as-outputs

**Comment by cnobles** [comment]
Resolved in #51.
