### ISSUE TITLE
generate_stat_report tries to parse iguide_dir from other arguments

### ISSUE THREAD

**Issue by ressy** [cnobles/iGUIDE#46]
I have a directory path with "...-iguide" in my analysis, and when [generate_stat_report.R greps](https://github.com/cnobles/iGUIDE/blob/master/tools/rscripts/generate_stat_report.R#L77) for "-i" in its argument list it finds that path and tries to figure out the iguide_dir setting from it.  Anchoring those two greps like "^-i" so it has to start at the beginning seems like a simple fix though.

**Comment by ressy** [comment]
Maybe like this? https://github.com/cnobles/iGUIDE/compare/master...ressy:generate-stat-report-args

**Comment by cnobles** [comment]
Fixed in #52 by converting over to argparser. This is consistent with the other scripts.
