### ISSUE TITLE
A failure in the middle of the run

### ISSUE THREAD

**Issue by iditbuch** [cnobles/iGUIDE#74]
Hi Chris,
<img width="836" alt="Screen Shot 2020-06-30 at 16 51 37" src="https://user-images.githubusercontent.com/50797134/86135110-0f049800-baf3-11ea-9ede-7577a246e840.png">
The attached file shows some error in the middle of the run.
Please help.

Thanks

Idit

**NOTE:** This run was done using the umi_alt method that you added just recently. So I just discovered that iguide works and completed the run when the parameter R1_Leading_Trim_ODN = "."   However, when set to R1_Leading_Trim_ODN = "ACGCGA"  (that's our case), the run fails ... 
Many thanks for your help !!

**Comment by cnobles** [comment]
Hi Idit,

That's interesting, as the point where it failed is all the way at the evaluation. Could you post the eval.log file? Additionally, if you look at your unique sites data object, do you see many genomic locations identified?

Sorry it has taken me some time to respond, Definitely a lot going on these days.

Best,
Chris

**Comment by iditbuch** [comment]
Dear Chris,

Thanks so much for your answer.
I retried the whole run, this time with R1_Leading_Trim_ODN=” "GCGAAC" and this time it worked perfectly.
Just few notes:

  1.  I had to remove the .snakemake directory each time before any rerun.
  2.  One iguide run needs a machine with at least 96GB RAM to complete successfully

One last question:
In your umi_alt_example.supp.csv file there are only two columns – specimen & comment. Is there a way to add a control (non-treated) sample such that its results will be deducted from the treated samples results ?

Many thanks,

Idit

**Comment by magic2077** [comment]
Hi Idit,

I installed iguide and it worked for simulation data. However when I run my real data (umi_alt method) I always got errors:

$ iguide run configs/run2.config.yml
ValueError in line 89 of /home/ubuntu/iGUIDE/Snakefile:
'sampleName' is not in list
File "/home/ubuntu/iGUIDE/Snakefile", line 89, in
File "/home/ubuntu/miniconda3/envs/iguide/lib/python3.6/site-packages/iguidelib/init.py", line 12, in import_sample_info

You mentioned that for each run you had to remove the .snakemake directory. Could you explain the reason? I am wondering if my run failed because I did not remove the .snakemake directory.

Thanks a lot!

Magic2077

**Comment by iditbuch** [comment]
Hi Magic2077,

A .snakefile directory preserves the data accumulated in the previous run trial that failed. So, obviously, it would be best to delete it before trying to run again.
As for the sampleName, I recommend reading the tutorial pages carefully.

Best of luck

Idit

**Comment by magic2077** [comment]
Hi Idit,

Thanks a lot for your explanation! That makes sense!

I am still working on figuring out sampleName not in list problem.

Best
Magic2077

**Comment by magic2077** [comment]
Hi Idit,

I run IGUIDE umi_alt pipleline but always got the following errors.

![image](https://user-images.githubusercontent.com/72854293/96639018-e983e000-12d5-11eb-8c30-429a6c02bf39.png)

Erros logs:

Versioning:
[1] run_set       soft.version  build.version
<0 rows> (or 0-length row.names)
Error in mutate_impl(.data, dots) : 
  Evaluation error: must be type logical, not double.
Calls: %>% ... <Anonymous> -> <Anonymous> -> mutate.tbl_df -> mutate_impl
Execution halted

I saw you had the same problem previously. Could you please give me some suggestion? Thanks a lot!

magic2077

**Comment by iditbuch** [comment]
Hi,
I'm currently on vacation. Will check it at the end of next week.
Idit

On Oct 20, 2020 11:15 PM, magic2077 <notifications@github.com> wrote:

Hi Idit,

I run IGUIDE umi_alt pipleline but always got the following errors.

[image]<https://user-images.githubusercontent.com/72854293/96639018-e983e000-12d5-11eb-8c30-429a6c02bf39.png>

Erros logs:

Versioning:
[1] run_set soft.version build.version
<0 rows> (or 0-length row.names)
Error in mutate_impl(.data, dots) :
Evaluation error: must be type logical, not double.
Calls: %>% ... -> -> mutate.tbl_df -> mutate_impl
Execution halted

I saw you had the same problem previously. Could you please give me some suggestion? Thanks a lot!

magic2077

**Comment by magic2077** [comment]
Hi Idit,

After carefully evaluatomg my sequencing data I found my read2 has very low quality. Only 90 reads contain the UMI sequences. I guess this is the reason for the failed run.

Enjoy your vacation!

Magic2077

**Comment by ShanSabri** [comment]
@cnobles + @iditbuch -- I have the exact same issue. How would you suggest correcting? I'm on a 128Gb instance and clear out my .snakemake before reruns.

**Comment by cnobles** [comment]
Just checking, @iditbuch, @magic2077, @ShanSabri, are these issues resolved or being handled in other threads?

**Comment by iditbuch** [comment]
resolved from my point of view. Thanks

**Comment by ShanSabri** [comment]
Resolved on my end - Thank you!
