### ISSUE TITLE
align errors

### ISSUE THREAD

**Issue by magic2077** [cnobles/iGUIDE#76]
Hi Chris,

Iguide data analysis pipeline is very useful for us. Thanks a lot for posting the pipeline in github!

I ran the simulation test but got error information as follows:

[Wed Oct 14 07:08:55 2020]
Error in rule align:
    jobid: 109
    output: /home/ubuntu/iGUIDE/analysis/simulation/process_data/align/iGXA.R1.bin2.psl
    log: /home/ubuntu/iGUIDE/analysis/simulation/logs/iGXA.R1.bin2.blat.log (check log file(s) for error message)
    shell:

    if [[ $(cat /home/ubuntu/iGUIDE/analysis/simulation/process_data/consol/iGXA.R1.bin2.consol.fasta | wc -l) -eq 0 ]]
        then
            touch /home/ubuntu/iGUIDE/analysis/simulation/process_data/align/iGXA.R1.bin2.psl
            echo 'Empty input sequences for /home/ubuntu/iGUIDE/analysis/simulation/process_data/consol/iGXA.R1.bin2.consol.fasta.' > /home/ubuntu/iGUIDE/analysis/simulation/logs/iGXA.R1.bin2.blat.log 2>&1
        else
            blat /home/ubuntu/iGUIDE/genomes/hg38.2bit /home/ubuntu/iGUIDE/analysis/simulation/process_data/consol/iGXA.R1.bin2.consol.fasta /home/ubuntu/iGUIDE/analysis/simulation/process_data/align/iGXA.R1.bin2.psl                 -tileSize=11 -stepSize=9 -minIdentity=85 -maxIntron=5 -minScore=27 -dots=1000 -out=psl -noHead > /home/ubuntu/iGUIDE/analysis/simulation/logs/iGXA.R1.bin2.blat.log 2>&1
    fi

        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job align since they might be corrupted:
/home/ubuntu/iGUIDE/analysis/simulation/process_data/align/iGXA.R1.bin2.psl
[Wed Oct 14 07:10:11 2020]
Finished job 116.
50 of 125 steps (40%) done

Could you please help me solve the problem?

Thanks a lot!

**Comment by magic2077** [comment]
Hi Chris,

After reinstall iGUIDE the simulation data worked. However when I run iguide using my real data (ALT iguide, library prep by simple protocol) I got errors:

$ iguide run configs/run2.config.yml
ValueError in line 89 of /home/ubuntu/iGUIDE/Snakefile:
'sampleName' is not in list
  File "/home/ubuntu/iGUIDE/Snakefile", line 89, in <module>
  File "/home/ubuntu/miniconda3/envs/iguide/lib/python3.6/site-packages/iguidelib/__init__.py", line 12, in import_sample_info


Any idea?

Thanks a lot!
Lijie

**Comment by cnobles** [comment]
Hi Lijie,

This looks like this could be a sample info file issue, formatting anyways. Would you mind pasting the first two lines of your sampleInfo file here? Additionally, the first part of the config could be helpful is figuring out the issue (just down to the dashed line is enough).

Best,
Chris

**Comment by magic2077** [comment]
Hi Chris,

The problem was solved. I used your sample information format and just changed the details by my project and it worked. Thanks a lot!

Lijie
