### ISSUE TITLE
Pipeline fails using multihits (typo in code)

### ISSUE THREAD

**Issue by ShanSabri** [cnobles/iGUIDE#82]
Error arises when `iGUIDE/tools/rscripts/assimilate_incorp_data.R` is called when `recoverMultihits = TRUE`.  

Error:
```
Error in stri_detect_regex(string, pattern, opts_regex = opts(pattern)) :
  object 'mulithit_files' not found
Calls: <Anonymous> -> stri_detect_regex
Execution halted
```

Solution fixing [this](https://github.com/cnobles/iGUIDE/blob/a17daec1755277b79a339ee3fb2812d5fd85397b/tools/rscripts/assimilate_incorp_data.R#L245) line (`args$multihit` --> `args$multihits`)

**Comment by cnobles** [comment]
Great catch, I'll work this in soon.

**Comment by cnobles** [comment]
Maybe didn't get to it as soon as I had expected. :) 

Found a couple additional bugs, but all sorted out in d7ed90ded9ce4611d543335fed4a871d18e76b2c. Check v1.1.1 when completed.
